### ISSUE TITLE
[data viz] Create function to plot a diverging stacked bar chart

### ISSUE THREAD

**Issue by SimonMolinsky** [hs3city/surveypie#5]
**BRANCH**:
`5-data-viz-create-function-to-plot-a-diverging-stacked-bar-chart`

Based on the chart from the tutorial here: https://ourcodingclub.github.io/tutorials/qualitative/ prepare a Python function that plots this kind of graph:

![Chart](https://ourcodingclub.github.io/assets/img/tutorials/qualitative/diverging_bar_likert.png)

You may use low-level graphical packages such as `matplotlib` or other packages that maybe offer the functionality to plot Diverging Stacked Bar Chart.

Use (and crate) a fake dataset for it, or read the same dataset as in the tutorial above. The best option to handle this task is to use `pandas` package.

Step-by-step guide:

- Check if there are Python graphical packages that can perform this task, if not, then use `matplotlib`.
- Create a virtual environment or conda environment.
- Install the graphical package of your choice and `pandas` in your environment.
- Load or create fake data (if you want to create a fake table then use Excel or Google Spreadsheets and save the table into csv).
- Develop a function to mimic functionality from the tutorial.
- If you use data from the tutorial, add link to data source and tutorial's author in your code.

It's a single script, but **use a custom branch from this issue instead of the `main` branch**. You may write your script in Jupyter Notebook or Python `.py` file. Use Python <= 3.10.

**Comment by PawelKinczyk** [comment]
I suggested @Arturstrag to plot chart in different way. Avoid splitting to "high" & "low". In my opinion we can get similar results by subtract percentage.

**Comment by SimonMolinsky** [comment]
I'm closing the issue because it was inactive for a long time.
